-- Customer data
MERGE INTO CUSTOMERS
    (CUSTOMER_ID,CREATED_TIME,EMAIL_ID,CUSTOMER_NAME,LAST_UPDATED_TIME)
    KEY (CUSTOMER_ID)
    values (1, current_time (),'test@gmail.com','Test', current_time ());

-- Hospitals data
MERGE INTO HOSPITALS(HOSPITAL_ID,CREATED_TIME,HOSPITAL_DESCRIPTION,HOSPITAL_END_TIME,HOSPITAL_START_TIME,HOSPITAL_NAME,LAST_UPDATED_TIME)
    KEY (HOSPITAL_ID)
    values (2, current_time,'Test Hospital','23:00:00','10:00:00','Test Hospital', current_time);
MERGE INTO HOSPITALS(HOSPITAL_ID,CREATED_TIME,HOSPITAL_DESCRIPTION,HOSPITAL_END_TIME,HOSPITAL_START_TIME,HOSPITAL_NAME,LAST_UPDATED_TIME)
    KEY (HOSPITAL_ID)
    values (3, current_time,'Manchester Hospital','23:00:00','10:00:00','Manchester Hospital', current_time);

-- Animals Data
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (100,'FARM_ANIMAL','Farm Animal','Cow', current_time (),'LOW', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (101,'FARM_ANIMAL','Farm Animal','Buffalo', current_time (),'LOW', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (102,'PET','Pet Animal','Dog', current_time (),'LOW', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (103,'PET','Pet Animal','Cat', current_time (),'LOW', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (104,'WILD','Wild Animal','Lion', current_time (),'HIGH', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (105,'WILD','Wild Animal','Tiger', current_time (),'HIGH', current_time ());
MERGE INTO ANIMALS(ANIMAL_ID,ANIMAL_TYPE,ANIMAL_CATEGORY,ANIMAL_NAME,CREATED_TIME,DANGEROUS_LEVEL,LAST_UPDATED_TIME)
    KEY (ANIMAL_ID)
    values (106,'ZOO','ZOo Animal','Bear', current_time (),'HIGH', current_time ());
